# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e33a2a86422923bc136e0dbfbffcc7cd564f772777898eb6238666ca26b337acdc0056775f85e40fb100a12d05f088999bb1127fa017f101c7ad8ffcd911f6f

test:
  secret_key_base: 5b4925546b36ae027780a8f6e935a5712fbfe0f5a467311a30abd64c623f84073eb13119665178f82579fe0f5362dbb4023ccdb5156e7fdb1c8fcc7c776352da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
